export const guideUpdated = '2026-09-01'

export const guideSections = [
  { title: 'Complete workflow', items: ['Connect Gmail with the local Desktop OAuth client.', 'Create a campaign, then add recipients manually or import CSV.', 'Upload files to the attachment library and select common or recipient attachments.', 'Preview originals, review blocked and previously sent rows, then type SEND ORIGINAL EMAILS.', 'Run Check replies for one campaign, or use Organizations > Check all replies to refresh every campaign and its last-checked timestamps.', 'Review organization outcomes and notes, then preview follow-ups, filter by age and organization, select rows, and type SEND FOLLOW-UP EMAILS.'] },
  { title: 'Organization tracking', items: ['Organizations combines matching organization names across every local campaign.', 'Check all replies is read-only: it checks each campaign, persists every recipient classification and checked time, then refreshes organization totals.', 'The workspace header shows the latest check time and each organization row shows its own latest persisted check.', 'Outcome and notes are manual. Choose Unreviewed, No response, Interested, Not interested, Follow up, or Other; the app never guesses the business outcome from reply text.', 'Organization CSV export follows the current search/outcome filters and includes last-checked time.'] },
  { title: 'Campaign management', items: ['Use the header actions to rename, duplicate, export, or delete the selected campaign.', 'Duplicate copies campaign defaults and recipients into a new campaign, but does not copy delivery, reply, or follow-up history.', 'Export downloads a local JSON snapshot. Delete removes only local campaign state and never deletes Gmail messages.', 'Deleting requires the exact confirmation text DELETE CAMPAIGN.'] },
  { title: 'Local settings', items: ['Settings can change the sender display name, default original subject, default template name, and daily send limit.', 'Settings also shows successful deliveries in the rolling last 24 hours, today in the backend local timezone, and today in UTC. These counts include originals and follow-ups.', 'Saved values apply to future previews, newly created campaigns, and outgoing messages without restarting localhost.', 'Existing campaign defaults are not rewritten when application defaults change.', 'The Gmail account is shown read-only. OAuth credentials and storage paths remain in the ignored appsettings.json file.'] },
  { title: 'Original HTML body', items: ['Paste HTML into HTML body override when you do not want to create a template file.', 'An explicit recipient template has highest priority. Otherwise manual HTML overrides organization and default templates.', 'Preview each recipient to inspect the final personalized HTML before sending. Leave the field blank to use template files normally.'] },
  { title: 'CSV format', items: ['Required headers: Name, Organization, Email.', 'Optional headers: Subject, Attachment, Template.', 'Attachment values are filenames only, such as resume.pdf. Quoted commas are supported.', 'Use Sample CSV beside Import CSV for a safe starting file. Imports update matching emails without erasing message history.'] },
  { title: 'Attachment rules', items: ['Each campaign has an isolated folder under resources/attachments/{campaign-id}.', 'Use a pipe between multiple CSV attachment filenames, for example resume.pdf|cover-letter.pdf.', 'Paths, path separators, rooted names, and .. are rejected.', 'Replacing an existing filename requires explicit approval. Referenced files cannot be deleted.', 'Preview batch shows and validates the final attachment list. Every file is checked again immediately before sending.'] },
  { title: 'Reply statuses', items: ['replied: a human reply from the recipient was found.', 'no-reply: no qualifying reply was found and the recipient may be eligible for follow-up.', 'automated: an automated response was detected.', 'bounced: a delivery failure was detected.', 'uncertain: Gmail content could not be classified confidently.', 'missing-thread: the original Gmail thread is unavailable.'] },
  { title: 'Filters and safety', items: ['Older than uses elapsed time since the latest outbound message.', 'Organization limits the visible follow-up candidates. Select visible selects only eligible filtered rows.', 'Previously sent original recipients stay visible but require Allow resend.', 'Reply checks and previews never send email. Follow-ups recheck Gmail immediately before dispatch.'] },
  { title: 'Troubleshooting', items: ['Gmail disconnected or expired: reconnect Gmail. Local authorization is required every two hours.', 'Missing attachment: upload the exact filename shown in CSV or recipient settings.', 'Recipient blocked: read the preview error, correct the campaign row, and preview again.', 'No follow-up candidate: run Check replies and confirm the status is no-reply and the minimum-age filter matches.'] },
] as const

export const placeholders = [
  { syntax: '{{name}} or {name}', value: 'Recipient first name', example: 'Hi Priya,' },
  { syntax: '{{organization}} or {organization}', value: 'Recipient organization', example: 'I am interested in Sample Technologies.' },
] as const
